cargo-generate/cargo-generate

.editorconfig, Cargo.toml, src/lib.rs, src/main.rs
Given a git URL, it'll
- ask for project name
- clone the repo
- replace `{{project-name}}`, `{{crate_name}}`, and `{{authors}}`
placeholder
- init a new repo
=> Add first draft of CLI

.appveyor.yml, .gitignore, .travis.yml, Cargo.lock, Cargo.toml, README.md
=> feat(test): add travis and appveyor

CONTRIBUTING.md
=> feat(contrib): create contributing.md

README.md
=> feat(readme): add installation and usage to readme

src/cargo.rs, src/git.rs, src/interactive.rs, src/main.rs, src/progressbar.rs, src/template.rs
=> refactor ALL THE THINGS

tests/integration/main.rs
=> Fix runnings tests multiple times on windows

Cargo.lock, Cargo.toml, src/emoji.rs, src/interactive.rs, src/main.rs, src/template.rs
=> feat(emoji): ✨⚠️⛔🔧

src/git.rs, src/main.rs, tests/integration/basics.rs
Closes https://github.com/ashleygwilliams/cargo-generate/issues/39
=> Fix cargo-generate

README.md, src/git.rs, src/main.rs, tests/integration/basics.rs
=> add cargo-gen

README.md, TEMPLATES.md
=> feat(templates): add list of templates

README.md, src/main.rs, tests/integration/basics.rs
#73 I just implemented the feature
=> add -n for --name

.travis.yml, Cargo.lock
=> chores chores chores

TEMPLATES.md
[Rendered](https://github.com/ashleygwilliams/cargo-generate/blob/b0ea548c5800fd9b78b7747160356e203e115c79/TEMPLATES.md)
=> Update TEMPLATES.md to include CLI template.

src/ignoreme.rs, tests/integration/basics.rs
fixes #97 
this is a pretty blunt test. curious what you think @DD5HT
=> Safety check

README.md, src/ignoreme.rs, tests/integration/basics.rs
=> feat(ignore): always ignore genignore

.travis.yml, Cargo.lock, Cargo.toml
=> feat(releases): travis deploy releases

src/ignoreme.rs
=> add check if genignore file exists

TEMPLATES.md
Adds https://github.com/eupn/rust-procmacro-quickstart-template to the list.
=> TEMPLATES.md: add procmacro-quickstart template

CHANGELOG.md
=> Fix PR links in CHANGELOG.md

README.md
=> Update README.md with latest install instructions

TEMPLATES.md
closes https://github.com/ashleygwilliams/cargo-generate/issues/185
=> fix dead link in TEMPLATES.md

src/template.rs, tests/integration/basics.rs
=> bug fix .github directory processing

TEMPLATES.md
`generust`, https://github.com/kyleu/generust
=> New template addition

TEMPLATES.md
Add OrbTk template to template overview.
=> Add OrbTk template

TEMPLATES.md
Added a WebAssembly template which can Create a quick Web assembly application with Rust
=> Added a WebAssembly template

README.md, src/template.rs, tests/integration/basics.rs
support operating system and architecture as a placeholder, resolves #251
=> support operating system and architecture

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md
This PR is a preparation PR for the next minor release. 
I collected all changes since v0.5.1 and crafted them into the CHANGELOG.md.
A few PR might still be collected before this one is merged.
=> release(v0.5.2): prepare the next minor release

Cargo.lock, Cargo.toml, src/config.rs, src/interactive.rs, src/lib.rs, src/project_variables.rs, src/template.rs, tests/integration/library.rs
=> Enable usage of custom keywords

.gitignore, Cargo.lock, Cargo.toml, README.md, src/app_config.rs, src/favorites.rs, src/lib.rs, tests/integration/favorites.rs, tests/integration/helpers/mod.rs, tests/integration/library.rs, tests/integration/main.rs
Implements favorites (shortcut) and reading of a configuration file, as partly described in #210
=> Feature favorites

.github/workflows/build.yml, README.md
this PR illustrates the usage of placeholders directly in the `README.md`
=> docs(placeholders): add some docs for placeholders to the readme

.github/workflows/e2e-test.yml
first PR to avoid things like #302 that happens mostly only on CI environments
=> feat(ci:e2e-test): inorder to verify things works

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md
the final PR for release 0.6.0, includes the final CHANGELOG and bumps the version
=> release(v0.6.0): add date+version+changes to the changelog

TEMPLATES.md
I made a little template for the Serenity Discord bot library. If it is of good enough quality, I wanted to add it here.
=> Add serenity template

README.md
- relates to #344 
- describe mandatory dependencies in order to prevent future issues like that
=> chore(docs): enhance vendored openssl installation

tests/integration/basics.rs
=> Add testcase for #201 (Test git history is removed)

src/interactive.rs
- templates can contain paramters with a list of options and a default
- this is now handled with the dialogouer capabilities for select from a list
- users can now choose via keys and don't need manual typing anymore
=> feat(templace:choices): better ux for template choice parameters

src/git.rs, tests/integration/basics.rs
If template fails to be cloned as a git repo (due to not being a repo!), try to just copy it as a plain folder.
This allows us to use plain folders as templates, and will make it easier when developing new templates.
Relates to #387
=> Allow template to be a plain folder.

Cargo.lock, Cargo.toml, README.md, src/lib.rs, src/template_variables/mod.rs, tests/integration/favorites.rs, tests/integration/library.rs, tests/integration/main.rs, tests/integration/values.rs
Relates to #389.
Just couldn't help myself 😄
=> Allow `--define` to specify values

README.md
closes #405 Suggestion: Cancel the need for PRs to maintain `TEMPLATES.md`
=> feat(templates): promote the new way of template sharing

README.md, src/app_config.rs
=> Allow cargo-generate.toml as alternative to cargo-generate.

README.md, src/app_config.rs, src/favorites.rs, src/git.rs, src/lib.rs, src/log.rs, src/template_variables/mod.rs, tests/integration/favorites.rs, tests/integration/values.rs
Fixes #389
Seems to also close #46
=> Allow specification of default template values

Cargo.lock, Cargo.toml, README.md, src/config.rs, src/lib.rs
=> Allow version requirement in `cargo-generate.toml`

README.md, src/args.rs, src/lib.rs, tests/integration/basics.rs, tests/integration/library.rs
=> Add `init` like behavior.

src/app_config.rs, src/lib.rs, src/template_variables/mod.rs
I like to fix random clippy lints from time to time, I hope it's appreciated 😂
=> fix additional clippy lints

CHANGELOG.md, Cargo.lock, Cargo.toml
probably the biggest release in my cargo-generate maintainer history, huge thanks to all you big efforts!
Without you this would never have been possible!!
@taurr @MarcoIeni @dave-tucker @orhun
=> release(0.9.0) version bump, readme, changelog

README.md
=> Added --path documentation

README.md
Solves [this](https://github.com/cargo-generate/cargo-generate/pull/428#issuecomment-904558608) comment.
=> README: specify minimum version for feature

Cargo.lock, README.md
@taurr anything that you would add?
=> docs(README): add a little starter guide for template ci testing

src/hooks/mod.rs, src/lib.rs
=> fix: Rhai variable extension not updating Liquid Object

src/lib.rs
=> fix: `cargo-generate.toml` not picked up on interactive template selection

README.md, src/template.rs, src/template_variables/authors.rs, tests/integration/basics.rs
=> feat: add username placeholder

src/hooks/variable_mod.rs
=> feature: add support for arrays in the variable::set Rhai script extension

Cargo.lock, Cargo.toml, src/interactive.rs
=> chore(deps): bump versions + fix #400

.github/workflows/release.yml
Do you want to substitute that link to https://github.com/Swatinem/rust-cache ?
=> ci: remove reference to unused action

Cargo.lock, Cargo.toml, README.md, src/git.rs, src/lib.rs
=> feat(#391): abbreviation support for gitlab and bitbucket users

src/git.rs, tests/integration/basics.rs
this PR fixes #79 by changes proposed in #93
=> fix(#79): improve the error message in case the repo or user does not exists

guide/book.toml
- Added git repository and edit url in guide/book.toml
=> chore(docs): added git url to book.toml

src/args.rs, src/hooks/file_mod.rs, src/hooks/mod.rs, src/hooks/system_mod.rs, src/hooks/variable_mod.rs, src/lib.rs, tests/integration/hooks.rs, tests/integration/library.rs
An attempt at #596.
I'm unsure if the command in Rhai should even try to return anything or if it should just "call and forget". But it might be useful to have the stdout (maybe even also stderr or whatever).
=> Allow system commands

Cargo.lock, Cargo.toml, src/git/gitconfig.rs, tests/integration/git.rs
Simple update of git_config.
It was left behind at v0.2 while the newest were v0.4 - Had to change minor stuff in the code.
=> Update git_config to 0.4.0

guide/src/README.md, src/lib.rs, tests/integration/filenames.rs
=> auto remove `.liquid` file extensions if present

CHANGELOG.md, guide/src/templates/builtin_placeholders.md, src/lib.rs, src/project_variables.rs, src/template.rs
=> feat: new `Rhai` variable: `is_init` ?

CHANGELOG.md, Cargo.lock, Cargo.toml, guide/src/templates/README.md, guide/src/templates/scripting.md, src/hooks/mod.rs, src/template.rs, src/template_filters.rs, tests/integration/basics.rs, tests/integration/hooks.rs
=> feat: make it possible to convert to `snake_case` and `kebab_case` from `Rhai`

src/app_config.rs, src/args.rs, src/git/mod.rs, src/git/utils.rs, src/lib.rs, src/user_parsed_input.rs, tests/integration/git.rs, tests/integration/helpers/project_builder.rs, tests/integration/library.rs
=> feat: support `--tag` in addition to `--branch`

CHANGELOG.md, guide/src/templates/scripting.md, src/hooks/file_mod.rs
=> feat: test for file existance from rhai scripts

TEMPLATES.md
Hey I haven't maintained that template in months... possibly years?
So I removed it from the list. I hope to avoid wasting anyone else's time with it.
=> Removed Serenity Template from Template List

src/hooks/mod.rs, src/lib.rs, tests/integration/hooks.rs
=> Variables set in pre scripts don't carry over to the template

src/args.rs, src/git/mod.rs, src/git/utils.rs, src/lib.rs
=> Git default branch is not honored when using --path

src/git/mod.rs, src/git/utils.rs, src/hooks/mod.rs, src/hooks/variable_mod.rs, src/interactive.rs, src/template_variables/authors.rs, src/template_variables/mod.rs, src/user_parsed_input.rs, tests/integration/basics.rs, tests/integration/conditionals.rs, tests/integration/config_file/defaults.rs, tests/integration/config_file/favorites.rs, tests/integration/config_file/values.rs, tests/integration/filenames.rs, tests/integration/git.rs, tests/integration/helpers/project_builder.rs, tests/integration/hooks.rs, tests/integration/online.rs
This is combination of:
- https://github.com/cargo-generate/cargo-generate/pull/779
- https://github.com/cargo-generate/cargo-generate/pull/778
which should make CI tests pass
closes #779
closes #778
=> Fix tests (1.65.0 toolchain support + git 2.38.1 compatibility)

src/lib.rs, tests/integration/basics.rs
Fixes: https://github.com/cargo-generate/cargo-generate/issues/758
=> When using --init, do not copy .git directories

CHANGELOG.md, Cargo.lock, Cargo.toml, src/interactive.rs
=> fix(#790): fix string template var prompts and default value presentation issues

CHANGELOG.md, Cargo.lock, Cargo.toml, src/interactive.rs
=> fix(#793): empty defaults are now back

src/args.rs, src/favorites.rs
=> '--list-favorites' option is broken

Cargo.lock, src/user_parsed_input.rs
=> fix(git:url): fix #752 short `owner/repo` github urls

Cargo.lock, Cargo.toml, README.md, src/favorites.rs, src/git/utils.rs, src/lib.rs, src/template_filters.rs, src/template_variables/project_dir.rs, tests/integration/basics.rs, tests/integration/config_file/defaults.rs, tests/integration/config_file/favorites.rs, tests/integration/git.rs, tests/integration/library.rs
Update revisions and git-config.
Fix clippy issues.
=> Bump revisions, update git-config

src/lib.rs
=> show a warning to the user if the template doesn't agree with the cli parameters

CHANGELOG.md, Cargo.lock, Cargo.toml
- CHANGELOG update
- dependency version updates
=> chore(release): prepare for v0.17.5

Cargo.lock, Cargo.toml, src/git/gitconfig.rs, tests/integration/git.rs
This fixes a compilation issue due to a recent `bstr` update.
This PR should fix #879 .
=> chore(deps): update `git-config` to `gix-config` (#879)

Cargo.lock, Cargo.toml
This PR bumps tempfile from 3.5 to 3.7
=> chore(deps): bump tempfile from ~3.5 to ~3.7

src/user_parsed_input.rs
=> fix: convert destination to absolute path

src/args.rs, src/template_variables/mod.rs, tests/integration/config_file/values.rs
- this fixes issue #947
- extend the regex to support empty values as well
=> fix: fix empty define values

src/hooks/system_mod.rs, src/hooks/variable_mod.rs, src/interactive.rs, src/lib.rs, src/project_variables.rs
Let me know if you have any uncertainty on my changes, as they modified quite a few things !
I can add more tests for `type = "text"` if you guide me where I should put them.
=> add Text and Editor type (close #1074)

src/lib.rs, src/project_variables.rs, src/template_variables/mod.rs
For demo see https://github.com/cargo-generate/cargo-generate/issues/1114#issuecomment-1993650476.
I am no sure about my namings, so it can be changed. Also fixed double whitespace in a related error message (which showed up when I was testing stuff).
Fixes #1114.
=> fix: default values are not ignored in silent mode

Cargo.lock, Cargo.toml, guide/src/templates/README.md, guide/src/templates/builtin_placeholders.md, guide/src/templates/scripting.hook-types.md, src/lib.rs, src/template_variables/project_dir.rs, src/template_variables/project_name.rs, src/template_variables/project_name_input.rs, src/user_parsed_input.rs, tests/integration/basics.rs, tests/integration/helpers/project_builder.rs, tests/integration/hooks_and_rhai.rs
- fixes #1152 
- keep either snake_case or dash-case if provided
- keep as it is when with force
- else change it to dash-case as it was always happening
- adjust the docs accordingly
=> feat(project-name)!: don't rename snake_case to hyphens in project name

guide/src/templates/authoring.md, guide/src/templates/scripting.rhai-extensions.md
=> fix(guide): very minor markdown fix

src/git/mod.rs
=> fix: tag option, see #1222

guide/src/README.md, guide/src/templates/ignoring.md, tests/integration/basics.rs, tests/integration/config_file/values.rs, tests/integration/filenames.rs, tests/integration/git.rs, tests/integration/helpers/arg_builder.rs, tests/integration/helpers/project_builder.rs
=> Clarify `.liquid` overwrite and ignore behavior

src/hooks/system_mod.rs
=> fix: inherit stdio for system::command calls

guide/src/SUMMARY.md, guide/src/templates/pitfalls.md
I hope this adds more clarity for issue #1397 and #843
=> docs: elaborate on common pitfalls that appeared to happen lately

example-templates/arrays/README.md.liquid, example-templates/arrays/cargo-generate.toml, guide/src/templates/template_defined_placeholders.md, tests/integration/template_config_file/placeholders.rs
- demonstrates the expectations on #1420 
- also adds more clarity on the version, relates to #1417
=> docs: clarity on arrays

src/workspace_member.rs
This pull request addresses [Issue #1442](https://github.com/OWNER/REPO/issues/1442), where the recent change in `cargo-util-schemas` made `package.name` optional. Previously, the code assumed `pkg.name.as_ref()` returned an `Option<...>`, causing a compile error. This update properly checks for the `[package]` section and uses `anyhow!` to bail out with a descriptive error if `package.name` is missing.
- Updated `WorkspaceMember::try_new` to safely unwrap `manifest.package()`.
- Replaced the old logic with a clearer `ok_or_else` pattern plus `anyhow!` for error creation.
- Ensured that if either `[package]` or `package.name` is missing, return a helpful error message instead of panicking or failing the compilation.
- Ran `cargo test` locally, confirming that all tests now pass on latest …
=> fix: handle optional package.name field in workspace_member (see #1442)

src/absolute_path.rs, src/user_parsed_input.rs
Signed-off-by: Sven Kanoldt <sven+oss@d34dl0ck.me>
=> fix: fix lints

.github/workflows/release-pr.yml
Signed-off-by: Sven Kanoldt <sven@d34dl0ck.me>
=> fix(ci): fix that checks on release pr, triggerd by a good old PAT

CHANGELOG.md
Tag begin with a "v" which needs to be included in the comparison links to work
=> Fix broken comparison links in CHANGELOG.md
