cargo-generate/cargo-generate

README.md
As discussed in #42, there are a few dependencies that have to be met before `cargo-generate` can be installed and run. I left out the installation of build-essential resp. a C compiler because it is already described in the [rust install guide](https://doc.rust-lang.org/book/second-edition/ch01-01-installation.html). Everybody developing with rust should already have this. The `openssl-sys` crate already described how to install the openssl library so I just added a link to their crate page.
=> Describe build & runtime dependencies in README

src/template.rs, tests/integration/basics.rs, tests/integration/helpers/mod.rs
=> fix crate_name

src/interactive.rs, src/main.rs, src/projectname.rs, src/template.rs, tests/integration/basics.rs
👾 do no merge 👾 
fixes #63 and adds tests for:
- when `--name` is passed to generate it should be kebab'd
=> test(case): project names are kebabs

src/main.rs, src/projectname.rs, src/template.rs, tests/integration/basics.rs
=> Add force flag to allow user defined project name

src/git.rs, src/main.rs, src/template.rs, tests/integration/basics.rs, tests/integration/helpers/project_builder.rs
This mimics the `--branch` option available when performing
a `cargo install` from git.
I created this without first noticing https://github.com/ashleygwilliams/cargo-generate/pull/87 but after some discussion here it seemed like it made sense to open this as an alternative that addresses issues related to assuming that "master" was always the default branch on the remote.
CC @deg4uss3r
=> Add support for specifying git branch

Cargo.lock, Cargo.toml, src/git.rs, src/main.rs, src/template.rs, tests/integration/basics.rs, tests/integration/helpers/project_builder.rs
Since cargo-generate doesn't set a credentials callback for
git2::Repository, it can't pull authenticated repos. Cargo provides an
[authentication callback](https://github.com/rust-lang/cargo/blob/6a7672ef5344c1bb570610f2574250fbee932355/src/cargo/sources/git/utils.rs#L409-L617) in `sources::git::utils::with_authentication`,
but the callback isn't public.
Rather than copying the callback to this repo, it was more maintainable
long-term to just let Cargo handle pulling git-repos and managing
submodules.
I also added a test for submodules and found a bug in the template
processing where submodules didn't have their git metadata excluded from
the template processing. So now the template processing excludes git
metadata no matter where it's located.
=> Use cargo to pull git remotes.

.appveyor.yml
This should build a release version only when it is building a tag, thus
fixing the problem where it does not back the exe final in the final
.tar.gz file.
=> Fix windows release on appveyor

TEMPLATES.md
I wrote two templates, one for quickly getting started creating rust embedded projects for the blue pill board, a very popular inexpensive micro controller board that I'm playing with and the other for setting up projects using my cmdr crate. I thought you might be interested in linking to these templates.
This is my first pull request on github so please let me know if I'm doing something wrong or silly or stupid or if there is any etiquette or naming convention that I should be following.
=> Add bluepill and cmdr template links to TEMPLATES.md

Cargo.lock, Cargo.toml, README.md, src/config.rs, src/ignoreme.rs, src/include_exclude.rs, src/lib.rs, src/template.rs, tests/integration/basics.rs
Adds support for a file which allows for templates to configure which files should be processed, either using a whitelist method (include), or a blacklist method (exclude), with include being preferred over exclude if both are present. This mirrors the behavior used by cargo for the configuration options of the same name in `Cargo.toml`, and uses some of the same code.
closes #144
closes #124
closes #48
closes #43
closes https://github.com/cloudflare/worker-emscripten-template/issues/1
=> Feature: Add file for configuring include / exclude of files to template

src/ignoreme.rs, tests/integration/basics.rs
Fixes a bug I introduced in #174, where the deletion part of `ignoreme.rs` would throw a confusing error message because it was trying to delete a file that didn't exist.
Closes #181.
=> Fix: Only try to remove files that exist

README.md, src/template.rs, tests/integration/basics.rs
PR #161 had some integration issues with #174, as well as some footguns.
- what to do about using template tags in filenames along with the include option in `cargo-generate.toml` when you can't specify a filename with curly braces in it ergonomically using glob syntax
- what to do about characters coming out of a template tag and being invalid when part of a filename.
Since #174 is unblocking lots of people and templates, we should revert #161 and go back to the design stage to figure out a more compatible way to allow for template creators to rename their files as part of generation.
=> Revert "Merge pull request #161 from k0pernicus/feat_template_tag_in_filename"

src/config.rs, src/lib.rs, tests/integration/basics.rs
```
🌀  🐑  Generating a new webpack worker project with name 'test504'...
🔧   Creating project called `test504`...
⚠️   Your cargo-generate.toml contains both an include and exclude list. Only the include list will be considered. You should remove the exclude list for clarity. ⚠️
Removed: "/Users/malonso/cf-repos/scratch/test504/.genignore"
Removed: "/Users/malonso/cf-repos/scratch/test504/cargo-generate.toml"
Removed: "/Users/malonso/cf-repos/scratch/test504/LICENSE_APACHE"
Removed: "/Users/malonso/cf-repos/scratch/test504/LICENSE_MIT"
✨   Done! New project created /Users/malonso/cf-repos/scratch/test504
```
warn emoji renders correctly in terminal
=> Add warning if config has include and exclude

src/lib.rs
This PR changes two instances where cargo-generate would "fail" but exit with code 0.
=> Fail on failures

src/ignoreme.rs
Fixes issue #192 Tested on Linux and windows, but not tested on Mac os x.
=> #192 fix paths \\ instead of \ on windows

src/template.rs, tests/integration/basics.rs
Fixes the filter macro names for `pascal_case` and `snake_case`.
Also, I checked the docs and only found info for the date filter. Should we add a note about how to use these other filters in the README?
Closes #180
=> Fix unknown filters

src/ignoreme.rs, src/lib.rs, tests/integration/basics.rs
This PR reduces the output for generate commands that ignore a lot of files. The old printout can be accessed with the `--verbose` flag.
My thinking behind this is that when people are running `cargo generate` on a given project, they probably don't care too much what the template is configured to ignore, but the output can definitely be helpful for the template maintainers.
**Before:**
```console
$ cargo generate --name my-site --git https://github.com/cloudflare/worker-sites-template
🔧   Creating project called `my-site`...
Removed: "/Users/averyharnish/Documents/work/_tmp/my-site/.genignore"
Removed: "/Users/averyharnish/Documents/work/_tmp/my-site/cargo-generate.toml"
Removed: "/Users/averyharnish/Documents/work/_tmp/my-site/LICENSE_APACHE"
Removed: …
```
=> Add verbose flag for printing removed files

Cargo.toml
One of our downstream dependencies broke semver, so currently `cargo install cargo-generate` fails. This PR makes us a binary explicitly, so when uploading to crates.io via cargo the lockfile is included so when a downstream dependency breaks semver, it doesn't break `cargo-generate`
=> Make cargo-generate a binary explicitly

TEMPLATES.md
The new template is here: https://github.com/usagi/template-rust-backend-with-electron-frontend
=> Add template-rust-backend-with-electron-frontend

TEMPLATES.md
Hi friends,
I built a swift-rust-xcode-template for building iOS apps so that people who don't have tons of xcode knowledge to get an ios-rust project started.
Feel free to open any issues on that repo if you can find them. I'm open to a better starter kit for this project. It's pretty much just hello world but with cbindgen, cargo lipo and 3 functions to show you how to get started piping data between swift and rust.
=> Added swift-rust-xcode-template to TEMPLATES

TEMPLATES.md
Project Repo: https://github.com/omarabid/rust-starter
The goal of Rust Starter is to have a basic CLI app with the most sane default and most popular Rust crates. Currently, it supports CLI (Clap), Configuration (config-rs), Error Chaining (Failure), etc...
- Documentation is yet to be written for the project.
=> add rust-starter

src/lib.rs, tests/integration/basics.rs
* ignores files listed in .genignore _before_ walking the project template and doing substitution 
This should fix scenarios where liquid variables are causing errors in files that are ignored. Fixes #236
=> ignore files in .genignore before walking/substitution

TEMPLATES.md
Add a link to [rust-cli-template] in `TEMPLATES.md`.
From the template's `README.md`, rust-cli-template includes:
- Decently filled out `Cargo.toml`
- Support for benchmarking with [Criterion]
- A bunch of useful default dependencies and dev-dependencies.
- [pretty_assertions] and [indoc] for tests
- [color_eyre] with [tracing], [tracing-subscriber], and [tracing-error]
for error reporting and logging
- [structopt] for command-line argument parsing (to be replaced with clap3
whenever that's released)
- A lib target for doc tests and a bin target for the actual tool
[Criterion]: https://github.com/bheisler/criterion.rs
[pretty_assertions]: https://docs.rs/pretty_assertions
[indoc]: https://docs.rs/indoc
[color_eyre]: https://docs.rs/color_eyre
[tracing]: https://docs.rs/tracing …
=> Add rust-cli-template to TEMPLATES.md

src/git.rs, src/lib.rs, tests/integration/basics.rs, tests/integration/helpers/project_builder.rs
Default to cloning the template repository's default branch, instead of hard-coding a default of `master` if `--branch` isn't given.
This has two benefits:
1. For repositories with a default branch other than `master`, `--branch` is no longer required when using `cargo generate`
2. If the user has `init.defaultBranch` ([new in Git 2.28.0](https://github.blog/2020-07-27-highlights-from-git-2-28/)) set to something other than `master`, the newly-created repository has that branch name.
As an added bonus, ~~when I~~ if a user with `init.defaultBranch` set to something other than `master` runs the integration tests, they don't all fail because the `master` branch can't be found.
(Re-do of #240 with renamed branch)
=>  Use default remote branch instead of `master`

Cargo.lock, Cargo.toml, src/git.rs, src/lib.rs
Hi,
Thank you for `cargo-generate` :heart: 
I would like to introduce this change to make `cargo-generate` more friendly with repositories that don't use "master" as the default branch. I think this is particularly relevant now that GitHub also uses "main" instead of "master".
I would have like to fix it on cargo directly but there are some compatibility issues. But I don't think this is an issue for `cargo-generate`. This is why I'm introducing this change here.
I was personally bothered by it because I tried to make a new template but it failed because I was using the "main" branch as default branch.
=> Handle default branch properly

src/ignoreme.rs, tests/integration/basics.rs
I was going to write a script that wraps `cargo-generate` and then automatically deletes this, but it's pretty easy to just add to the default ignore set.
This file serves no purpose and causes clutter, and many users either fail to notice it or think it should be kept: https://sourcegraph.com/search?q=file:.cargo-ok&patternType=literal
I suspect any case where this file is actually part of the template is either broken or at best fragile (as it's existence can prevent cargo from detecting failure to extract the tarball), depending on cargo's behavior. (That said, if any do exist, it seems very likely they came into existence by something like using `cargo-generate` to generate a template repo).
Fixes #259
=> Ignore .cargo-ok files by default.

.github/workflows/build.yml, .github/workflows/release.yml, Cargo.lock, Cargo.toml, README.md, tests/integration/basics.rs, tests/integration/helpers/project.rs, tests/integration/helpers/project_builder.rs
this PR should fix all clippy + fmt related issues and should lead to a green build
Update: also bumps dependencies to their latest versions
=> fix(tests): make clippy happy

src/git.rs, tests/integration/basics.rs, tests/integration/helpers/project.rs, tests/integration/helpers/project_builder.rs, tests/integration/library.rs
When generating templates inside an existing repository, there is no need to attempt the initialization of a new one - in fact it just makes it harder to integrate the new template!
=> dont init git when inside existing repo

src/lib.rs, tests/integration/basics.rs, tests/integration/library.rs
#244 asks for an option to specify NOT to initialize the git repository.
This implements such an option, with possibility to be expanded into
other VCS systems.
=> Add --vcs option to avoid initializing git repo

src/interactive.rs, src/lib.rs, src/project_variables.rs
This PR does this:
- when the user is prompted to enter a value, enter key did not lead to use the default
now the in brackets presented default will be used, once the user hits enter
- also: refactor the interactive project / crate variable collection to reuse the
based interactive way, in order to eat your own dogfood
=> feat(variables): enter leads to default

Cargo.lock, README.md, src/app_config.rs, src/emoji.rs, src/favorites.rs, src/lib.rs, src/log.rs, tests/integration/favorites.rs
this PR ensures backwards compatibility to v0.5.x so that the favorite feature does not create any harm for long term users. So in detail that looks like this:
- when a user provides an argument such as `sassman/hermit-template-rs` without `--git`
- then this is looked up in the favourites but in case it is missing
we log a warning and use it as a git repo as if the user provided `--git sassman/hermit-template-rs`
- so we remain backwards compatible
- a user will likely notices about the favorites feature (warning message)
- insteaf of failing handle what the user want more gracefully, more peace of mind
=> feat(favorites:fallback): backwards compatibility

.github/workflows/build.yml, Cargo.lock, Cargo.toml, README.md, src/emoji.rs, src/git.rs, src/lib.rs, tests/integration/basics.rs, tests/integration/library.rs
this PR adds support for ssh remote urls
- support public ssh remote repository urls start with `git@` and `ssh://`
- support private ssh remote repositories
- add a public and an ignored private repo test (ignored because of ci/cd)
- todo: documentation
- use dir dependency to get home direction in a cross-platform manner
- refactor git checkout, to use now close and repository builder
- make clippy happy
- based on @SkamDart's PR [#328](https://github.com/cargo-generate/cargo-generate/pull/328)
- Resolves #325
=>  feat(remote:ssh): support for ssh remote urls

Cargo.lock, src/git.rs
- fixes #375
- retry n times, with a pause on process blocking error
- skip cleanup after retry
- the solution is to drop first all git related structs before removing the history
=> fix(git:cleanup): fix for #375

.github/workflows/release-binary-assets.yml
Add a workflow to build and upload binaries for common targets as release assets. This runs asynchronously as a separate workflow once a release is created. Each target is built and uploaded in parallel.
For example creating https://github.com/jashandeep-sohi/cargo-generate/releases/tag/v0.7.2-alpha.1 kicked off https://github.com/jashandeep-sohi/cargo-generate/actions/runs/1051298124 which eventually populated the assets.
=> Prebuilt binaries workfow for common targets

.github/workflows/build.yml, tests/integration/basics.rs
- GH Actions does not allow sharing secrets to PRs from forks
- this requiers to rethink the private repo test case
- for now I disable the test case so that PRs from forks stop failing
=> fix(ci): temp. workaround for GH Actions limitations

README.md, src/app_config.rs, src/config.rs, src/favorites.rs, src/lib.rs, tests/integration/favorites.rs, tests/integration/library.rs
This change allows to specify a sub-folder inside a git repository for use as the template.
By doing so, it allows us to e.g. generate projects from examples inside a repo, or to have a repo that contains multiple templates.
Relates to #47 and #78 
This pull-request will also make #295 obsolete, as there is no need to specify folders as templates, and thus we avoid a lot of the problems specified in #295 and #291, allowing for easier implementation of #291 (and thus #211).
@sassman Sorry for the long timeout here - as it seems we get no feedback for #295, I suggest this one instead. I still like the idea of `--pick` for #291, but it kinda conflicted and this is my proposal to remedy that!
=> Feature: specify subdir in repo as template

Cargo.lock, Cargo.toml, README.md, src/filenames.rs, src/include_exclude.rs, src/interactive.rs, src/lib.rs, src/template.rs, tests/integration/basics.rs, tests/integration/filenames.rs, tests/integration/helpers/project.rs, tests/integration/main.rs
- solves #159 and is partially based on PR #174
- addresses some issues from PR #182
> what to do about characters coming out of a template tag and being invalid when part of a filename
- now filenames are sanitized after templating
> what to do about using template tags in filenames along with the include option in cargo-generate.toml when you can't specify a filename with curly braces in it ergonomically using glob syntax
- simply not supported, hence exclusion must be configured with the filename before substitution.
- add tests to check for exploitation
- README.md updated
=> feat(template:filenames): template filenames now

src/app_config.rs, src/emoji.rs, src/favorites.rs, src/lib.rs
Improves the output of `--list-favorites` to be more in line with the normal output.
Also moves where the `AppConfig` is read. As it is more of a global config file than solely for favorites.
=> Improve output of --list-favorites.

README.md, src/filenames.rs
This commit allows for directories to also contain template tags
The use case for this would be creating a template that contained multiple crates, where the directory name for those crates could be derived from the template.
=> filenames: allow directory to contain template tag

src/template.rs, tests/integration/filenames.rs
In order to properly allow for templates in directory names, we must
adjust the WalkDir to include both files and directories AND to yield
contents first.
Given that the project name is bar, and the directory tree:
| {{project-name}}/foo.rs
| {{projcet-name}}
- {{project-name}}/foo.rs is read and the contents rendered
- fs:create_dir_all will create the bar directory
- fs::write will write bar/foo.rs
- the {{project-name}} directory is then deleted with fs::remove_dir_all
Which will provide:
| bar/foo.rs
Fixes: #396
Command output from this commit:
```
🔧   Creating project called `foo`...
[ 1/12]   Done: .appveyor.yml
[ 2/12]   Done: .gitignore
[ 3/12]   Done: .travis.yml
[ 4/12]   Done: Cargo.toml
[ 5/12]   Done: LICENSE_APACHE
[ 6/12]   Done: LICENSE_MIT
[ 7/12]   Done: README.md
[ …
```
=> template: Process Directories and Files

.github/workflows/release-binary-assets.yml
@sassman, I'm proposing a few changes to the prebuilt binaries workflow:
- Only use cross for linux builds. It's not really needed for macos & windows. On windows it also causes binaries to be built without the .exe extension.
- Try running running the built binary as a sanity check. Should we also be running tests for each of the targets too?
- Lock down the release action to a specific version & set `omitPrereleaseDuringUpdate` to avoid resetting the pre-release state of a release.
=> Only use cross for linux prebuilt binaries

README.md, src/template_variables/mod.rs, tests/integration/values.rs
Relates to #389
- Accepts env var `CARGO_GENERATE_TEMPLATE_VALUES_FILE` to specify the `template-values-file` option.
- Accept env vars on the form `CARGO_GENERATE_VALUE_<key>`, to set individual values (akin to `--define`)
> NOTE: Windows does **not** support passing in values for lowercase variables via the environment variables. Windows insist on using uppercase for all ENV vars.
=> Specify values via env vars.

src/app_config.rs, src/args.rs, src/favorites.rs, src/lib.rs, tests/integration/basics.rs, tests/integration/library.rs
Closes #406
Relates to #47 
Introduce `--path <path>` to use a local folder as the template.
This solves the issue of being unable to use a local 'dirty' git repo as the template. This would e.g. be the case during template development if the developer doesn't commit between each retry (which seems like a very likely scenario).
=> Introduce `--path` flag

src/git.rs
This PR removes the assumption from `should_canonicalize` test that is always being run in a subdirectory which is in `/home`.
For example, while building `cargo-generate` for Arch Linux in a clean chroot, tests are being run in `/build/cargo-generate/src` and this canonicalize test is failing as expected:
```
thread 'git::should_canonicalize' panicked at 'assertion failed: canonicalize_path(&PathBuf::from(\"../\")).unwrap().starts_with(\"/home/\")', src/git.rs:106:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
=> fix(tests:linux): use the current directory for canonicalize result

src/interactive.rs
while waiting for mitsuhiko/dialoguer#125, manually enable paging in dialoguer.
Related to #400 
Still feel like we should wait until `dialoguer` make their next relase for closing #400 though, as we should enable `fuzzy-search` too (already on their master)
=> feat: enable paging for long choice lists

src/filenames.rs, src/template.rs, tests/integration/basics.rs
this PR replaces the first draft at #245 also it fixes #204 and #205
it handles:
- undefined, but from a template requested variables cases harm, especially when a file contains a lot of them but was not excluded from parsing
- this PR addresses this issue by keeping unknown variables are they are, so that essentially files are partially processed after all
- matching variables are replaced undefined variables are ignored and kept as they were originally
=> feat(template:parsing): handle undefined variables gracefully

src/args.rs
I noticed that those parameters are not used when the `list_favorites` flag is passed, so in theory they should be treated as conflicts, right?
=> enumerate list_favorites conflicts

.github/workflows/build.yml, src/git.rs, src/lib.rs, src/main.rs, src/template_variables/authors.rs
I also:
- removed `--all` which is deprecated, in favor of `--workspace`
- surrounded with `<>` the markdown links, so that they are clickable from the docs
- removed duplicate documentation in main.rs, which is available in lib.rs
=> ci: add documentation check

README.md
I think that having a version specified as `">=0.8.0"` is more common than `">0.8.0"`.
Maybe in the copy paste, one may forget to add the `=` and this can lead to an error.
=> README: improve cargo_generate_version example

README.md
`cargo-generate` is recently moved to the [community] repository: https://archlinux.org/packages/community/x86_64/cargo-generate
This PR updates README.md to include the installation instructions for Arch Linux.
=> docs(readme): add installation instructions for Arch Linux

src/app_config.rs, src/args.rs, src/config.rs, src/emoji.rs, src/favorites.rs, src/git.rs, src/ignore_me.rs, src/include_exclude.rs, src/interactive.rs, src/lib.rs, src/progressbar.rs, src/project_variables.rs, src/template.rs, src/template_variables/authors.rs, src/template_variables/crate_type.rs, src/template_variables/mod.rs, src/template_variables/os_arch.rs, src/template_variables/project_name.rs
Went through the list of clippy warnings and added some that makes sense - such as using `pub(crate)` in private modules.
=> refactor: add more clippy warnings

Cargo.lock, Cargo.toml, src/git.rs, src/template_variables/crate_type.rs
cargo dependency was originally added in https://github.com/cargo-generate/cargo-generate/pull/119, but it doesn't seem to do what it was supposed to do now, so I think cargo-generate doesn't have to depend on it now.
=> Remove cargo dependency

Cargo.lock, Cargo.toml
closes #453
closes #452
closes #451
closes #449
closes #448
=> Save 33% in size on release binary, bump dependencies

src/config.rs, src/interactive.rs, src/lib.rs
This lets the user specify the base path (or git repo) for a potential multi-template repo. If there's more than 1 template in the repo, the user is asked to select the one to expand.
Given the user specifies a template folder without `cargo-generate.toml`, look for the config in child dirs. Then depending upon the number of configs found do:
0 => use the user specified folder
1 => use the folder with the found config
2+ => prompt the user for which template to use.
=> feat: prompt for subfolder upon multiple templates

README.md
In this way strings that start or end with a letter are not matched.
Otherwise strings like `a22` or `321b` are recognized as `phone_number`.
=> README: fix example regex

src/project_variables.rs
=> fix: print regex error

.cargo/audit.toml
This will fix the `audit` step that is failing in CI.
The same file is used in [tokio](https://github.com/tokio-rs/tokio/blob/master/.cargo/audit.toml)
=> maintenance: whitelist `time` advisories

Cargo.lock, src/git.rs, src/lib.rs, tests/integration/basics.rs, tests/integration/helpers/project.rs
- now also for local folders e.g. via `--path` the `.git` repo is fresh and clean initialized as expected
- test case is added
- other test case is refined
- this fixes #510
=> fix(#510): Using `--path` bring the `.git` folder from the source with it

src/lib.rs
- add a more specific error message to provide more context
- fixes #526
=> feat(#526): template sub directory error lacks context

Cargo.lock, Cargo.toml, src/git/mod.rs, src/git/remote.rs, src/git/utils.rs, src/lib.rs, tests/integration/git.rs
- fixes #520 
- implement gitconfig parsing
- use `insteadOf` configuration if available
- log some infos about the usage of the new rewritten remote url
- update used dependencies
=> feat(#520): Support Git's https to ssh rewriting configuration

src/app_config.rs
Not really an issue anymore, but converting a relative `--config` path into absolute form makes it easier to read/interpret the output of `cargo-generate`
Fixes #543
=> `--config` should behave relative to `CWD`

src/app_config.rs
Simply removes the "Unable to load config file" warning. I personally find this quite noisy and unnecessary.
=> Less noise

.github/workflows/release-binary-assets.yml
Include target `x86_64-unknown-linux-gnu` in the matrix so release packages are also generated for this target.
=> Generate release packages for `x86_64-unknown-linux-gnu`

.github/workflows/release-binary-assets.yml, src/git/utils.rs, src/lib.rs
the reason of https://github.com/cargo-generate/cargo-generate/issues/619  is to delete _.git_ folder, so  instead of deleting _.git_, I don't copy _.git_
=> Avoid panic caused by deleting git folders

Cargo.lock, Cargo.toml, src/args.rs, src/main.rs
Hello there!
I made this PR to replace `structopt` by `clap`.
I also derive `Clone` and `Debug` so it will be easier to use  `Args` from the public API.
Possible breaking change but `structopt` is on maintenance since Clap v3.1.0
=> Replace `structopt` by `clap`

src/args.rs, src/lib.rs, src/main.rs, tests/integration/basics.rs, tests/integration/library.rs
Hello there!
I made this PR to add the `dest` argument to the `generate` function.
This argument override the destination of the project if we give a path to the `generate` function.
If we give `None`, the behaviour stay the same as expected.
This is a breaking change btw, if you have suggestions to avoid that?
=> Override project_dir when using `generate()`

src/lib.rs
=> output from a *POST* `rhai` script is seemingly output *before* expansion.

src/app_config.rs, src/favorites.rs, src/lib.rs, src/main.rs, tests/integration/helpers/project.rs, tests/integration/library.rs
Hello there!
This PR aims to return the path of the generated project from the `generate` function.
Allowing the user of the public API to re-use the path when they can't guess the folder name of the generated project.
The changes there are quite big for this not so big goal, I you have any suggestions to make it clearer.
=> Return the path of the generated project from the `generate` function

Cargo.lock, Cargo.toml, src/args.rs, src/lib.rs, src/main.rs, tests/integration/library.rs
This is an attempt at supporting `--test` for running `cargo --test` inside the temporary folder where the template is expanded.
The implementation is now 100% in line with the original feature request.
* Anything after the `--test` on the command line is forwarded to the `cargo test` command.
* If needed, the user can specify a `CARGO_GENERATE_TEST_CMD` environment variable, whose contents will be used instead of `cargo test`, thereby making the command work for non Rust templates.
* User does not have to specify a project-name, as one will be generated.
* `--test` can not be used with `--git`, `--path` or `--favorite`. If will *always* use `--path .` internally.
* If a favorite/subfolder is specified, it will be interpreted as a subfolder of $CWD.
Fixes #455
=> Support `--test` for running tests on the expanded template

.github/workflows/release-binary-assets.yml
As discussed in #708, this step was failing and causing the `Release Binary Assets` action to fail. I've commented it out in the meantime to relaunch the action and generate binaries.
=> Remove `Smoke Test` step

src/template.rs, tests/integration/filenames.rs
=> renaming files by using e.g. `{{project-name}}.yml` as filename doesn't remove the original file

src/config.rs, src/hooks/file_mod.rs
After fixing the issue of cargo generate leaving the original file after renaming using placeholders, the template would fail if the template author had mittigated this by deleting the file from rhai... rhai failed if deleting a file that isn't there.
=> Deleting_a_non_existing_file_should_not_fail

guide/src/templates/authoring.md
The link to the `cargo-generate` Github Action was a little weird, fix it and point to the action in the marketplace.
=> Fix link to Github Action

.github/workflows/release-binary-assets.yml
Add `aarch64-apple-darwin` to the list of targets.
=> Add `aarch64-apple-darwin` release package

.github/workflows/build.yml, guide/src/templates/scripting.hook-types.md, src/git/utils.rs, src/hooks/variable_mod.rs, src/user_parsed_input.rs, tests/integration/config_file/favorites.rs, typos.toml
Resolve https://github.com/cargo-generate/cargo-generate/issues/761.
Since this is a Rust project, we'll use
https://github.com/crate-ci/typos which is equivalent to https://github.com/marketplace/actions/codespell-action and more suitable for Rust codebase.
=> Extend the GitHub CI build pipeline for spellchecks

src/args.rs
Provides a `Default` trait implementation for `GenerateArgs` and
`TemplatePath` in order to provide better ergonomics when using
`cargo-generate` as a lib.
---
Also fixes clippy warnings.
=> feat: impl `Default` for `GenerateArgs` and `TemplatePath`

Cargo.lock, Cargo.toml, src/args.rs
=> chore(deps): bump clap from 3.2.22 to 4.0

src/args.rs
Hello there.
A little PR to unleash the power of the new `Clap` API.
I added testing for the CLI (see [this](https://docs.rs/clap/latest/clap/_derive/_tutorial/index.html#testing))
I also replaced `#[clap(...)]` by `#[command(...)]` or `#[arg(...)]` to follow the reference from the v4.0
=> Update `derive` attributes for clap and add a test for the CLI

Cargo.toml, guide/src/installation.md
this makes it easier for downstream repos to use the system libraries without having to patch cargo-generate
`vendored-openssl` was previously not a default feature, but since we were using `git/vendored-openssl` unconditionally, it was still enabled by the default
=> build: put vendored libraries behind features

Cargo.toml, guide/src/installation.md
As reported in #883 it seems to be not that simple to build OpenSSL on windows. 
cargo-generate before the version `0.18` had vendored openssl as opt in default behaviour. That seemed to work quite ok on windows.
This PR turns back time and sets the feature `vendored-openssl` as opt-in by default.
=> fix(openssl): make feature `vendored-openssl` opt in by default

src/lib.rs
This PR fixes [#942 ](https://github.com/cargo-generate/cargo-generate/issues/942)
=> Add type annotation to avoid ambiguity introduced in bstr 1.5.0 (#942)

guide/src/templates/include_exclude.md
Presumably this used to be a section in include_exclude.md, but is now its own page.
=> Fix link to 'ignoring files'

src/config.rs, src/git/gitconfig.rs, src/git/mod.rs, src/git/utils.rs, src/lib.rs, tests/integration/helpers/project_builder.rs
In rare cases, if a generate operation is forcefully cancelled/panics, the tempdir used for git cloning might not be cleared up.
The default `.tmp` prefix leaves the tempdir hidden and hard to know which program created it.
Having `cargo-generate` prefix adds clarity and visibility.
The same is true when running tests, for instance if you cancel the pre-push hook.
=> fix: use tempdir prefix

Cargo.lock, Cargo.toml
chore(deps): bump sanitize-filename from 0.4.0 to 0.5.0
chore(deps): bump log from 0.4.19 to 0.4.20
chore(deps): bump regex from 1.9.1 to 1.9.4
chore(deps): bump indicatif from 0.17.5 to 0.17.6
chore(deps): bump openssl from 0.10.55 to 0.10.57
chore(deps): bump serde from 1.0.175 to 1.0.179
chore(deps): bump gix-config from 0.26.1 to 0.27.0
chore(deps): bump indexmap from 1.9.3 to 2.0.0
=> chore(deps): bump several versions

Cargo.lock, Cargo.toml, src/lib.rs
I.e. messages that include the file or directory that caused the error.
I was building a new template using `cargo-generate` today and I got stuck on a "File name is too long" error. No way to find out what file was causing the issue, even by passing `--verbose` to the CLI. Hence this PR!
After the change, I was able to immediately pinpoint the file and get unblocked.
=> feat(error): use `fs_err` instead of `std::fs` to provide actionable error messages

src/app_config.rs, src/args.rs, src/git/utils.rs, src/lib.rs, src/user_parsed_input.rs, tests/integration/git.rs, tests/integration/helpers/arg_builder.rs, tests/integration/helpers/project.rs, tests/integration/public_api.rs
`cargo-generate` currently supports `branch` and `tag` as mechanisms to select which revision of a `git` template should be used to generate the new project.
This PR adds support for arbitrary revisions—e.g. commit SHAs.
This aligns `cargo-generate` with `cargo`, which supports `rev` as a way to specify the specific revision of a `git` dependency.
I found myself looking for this feature when working on `pavex new` in [Pavex](https://github.com/LukeMathWalker/pavex). I want to store the template alongside the `pavex` binary and version them in lockstep: `pavex new` always relies on the template at the commit SHA that was used to compile the `pavex` binary, ensuring compatibility.
=> feat: Add support for generating from a specific git revision of a git template

guide/src/installation.md
=> chore: Update Arch Linux package URL in installation.md

src/args.rs, src/git/mod.rs, src/git/utils.rs, src/lib.rs, src/user_parsed_input.rs, tests/integration/public_api.rs
`cargo-generate` is typically used for generating templates from small repos. However, we would like to use it on [our repo] where the template lies in a larger mono-repo with git submodules that are not necessary to the template. The template is kept in this repo to failitate testing the various components within this repo. In this situation, the submodule download can add significat overhead to the initialization of the repo. Some have reported running our template generation command for tens of minutes and impacts the usability of our tool.
This change makes submodule cloning optional by adding a `--skip-submodules` flag that callers can set when using cargo-generate crate functions. This change intends the default behavior to clone submodules if they exist.
[our repo]: …
=> add --skip-submodules flag to optionalize cloning git submodules

CHANGELOG.md, Cargo.lock, Cargo.toml
* `cargo-generate`: 0.19.0 -> 0.20.0 (⚠️ API breaking changes)
```
--- failure constructible_struct_adds_field: externally-constructible struct adds field ---
Description:
A pub struct constructible with a struct literal has a new pub field. Existing struct literals must be updated to include the new field.
ref: https://doc.rust-lang.org/reference/expressions/struct-expr.html
impl: https://github.com/obi1kenobi/cargo-semver-checks/tree/v0.30.0/src/lints/constructible_struct_adds_field.ron
Failed in:
field GenerateArgs.skip_submodules in /tmp/.tmpjBgmvV/cargo-generate/src/args.rs:126
```
</p></details>
---
=> chore: release v0.20.0

Cargo.lock, Cargo.toml
Updating anyhow v1.0.81 -> v1.0.82
Updating cc v1.0.90 -> v1.0.96
Updating either v1.10.0 -> v1.11.0
Updating fastrand v2.0.2 -> v2.1.0
Updating getrandom v0.2.12 -> v0.2.14
Updating gix-config v0.36.0 -> v0.36.1
Updating gix-fs v0.10.1 -> v0.10.2
Updating gix-trace v0.1.8 -> v0.1.9
Updating gix-utils v0.1.11 -> v0.1.12
Updating hashbrown v0.14.3 -> v0.14.5
Updating jobserver v0.1.28 -> v0.1.31
Updating libc v0.2.153 -> v0.2.154
Updating libredox v0.0.1 -> v0.1.3
Updating lock_api v0.4.11 -> v0.4.12
Updating memchr v2.7.1 -> v2.7.2
Updating openssl-sys v0.9.101 -> v0.9.102
Updating parking_lot v0.12.1 -> v0.12.2
Updating parking_lot_core v0.9.9 -> v0.9.10
Updating pest v2.7.8 -> v2.7.10
Updating pest_derive v2.7.8 -> v2.7.10
Updating pest_generator v2.7.8 -> v2.7.10
Updating pest_meta …
=> chore(deps): update locked dependencies + bump rhai from 1.17.1 to 1.18.0

CHANGELOG.md, Cargo.lock, Cargo.toml
* `cargo-generate`: 0.20.0 -> 0.21.0 (✓ API compatible changes)
<blockquote>
[0.21.0]: <REPO>/compare/0.20.0...0.21.0
- Add the cargo-binstall installation method
- Don't rename snake_case to hyphens in project name ([#1172](https://github.com/cargo-generate/cargo-generate/pull/1172))
- Small reformatting only
- Enable the sponsor button
- Update locked dependencies + bump rhai from 1.17.1 to 1.18.0 ([#1182](https://github.com/cargo-generate/cargo-generate/pull/1182))
- Release plz can now force push
- Very minor markdown fix ([#1166](https://github.com/cargo-generate/cargo-generate/pull/1166))
- Fix changelog creation config file, regarding the unreleased section
</blockquote>
</p></details>
---
This PR was generated with …
=> chore: release v0.21.0

Cargo.lock, Cargo.toml, guide/src/templates/scripting.rhai-extensions.md, src/hooks/system_mod.rs, tests/integration/hooks_and_rhai.rs
Most license files start with a copyright statement with a year but `cargo-generate` hooks or template parameters do not provide access to that information . The only alternatives would be using the `system::command` API but that isn't something that is very portable and prompting the user for the year which is less than ideal. This PR adds a new API `system::date` which returns an object with 3 properties, `year`, `month`, `day`. This would allow for generating a license from a rhai hook:
```rhai
file::write(license.txt, `Copyright ${system::date().year} ${authors}
...
`);
```
I've also added docs for the `system` module, though I don't know if they cover the details outlined in #616.
=> feat(rhai-hooks): add a date API that provides year, month and day access

Cargo.lock
chore(deps): update several dependencies
Updating anstream v0.6.13 -> v0.6.14
Updating anstyle v1.0.6 -> v1.0.7
Updating anstyle-parse v0.2.3 -> v0.2.4
Updating anstyle-query v1.0.2 -> v1.1.0
Updating anstyle-wincon v3.0.2 -> v3.0.3
Updating anyhow v1.0.83 -> v1.0.86
Updating autocfg v1.2.0 -> v1.3.0
Updating cc v1.0.96 -> v1.0.99
Updating clap v4.5.4 -> v4.5.7
Updating clap_builder v4.5.2 -> v4.5.7
Updating clap_derive v4.5.4 -> v4.5.5
Updating clap_lex v0.7.0 -> v0.7.1
Updating colorchoice v1.0.0 -> v1.0.1
Updating crossbeam-utils v0.8.19 -> v0.8.20
Updating either v1.11.0 -> v1.12.0
Updating errno v0.3.8 -> v0.3.9
Updating getrandom v0.2.14 -> v0.2.15
Updating gix-actor v0.31.1 -> v0.31.2
Updating gix-date v0.8.5 -> v0.8.6
Updating gix-features v0.38.1 -> v0.38.2
Updating gix-glob …
=> chore(deps): update several dependencies

CHANGELOG.md, Cargo.lock, Cargo.toml
* `cargo-generate`: 0.21.0 -> 0.21.1
<blockquote>
[0.21.1]: <REPO>/compare/0.21.0...0.21.1
- Add a date API that provides year, month and day access ([#1201](https://github.com/cargo-generate/cargo-generate/pull/1201))
- Fix use of `bool` instead of `boolean` in the guide and add new types to error message ([#1203](https://github.com/cargo-generate/cargo-generate/pull/1203))
- Update several dependencies ([#1209](https://github.com/cargo-generate/cargo-generate/pull/1209))
</blockquote>
</p></details>
---
=> chore: release v0.21.1

CHANGELOG.md, Cargo.lock, Cargo.toml, cliff.toml
* `cargo-generate`: 0.21.1 -> 0.21.2
<blockquote>
[0.21.2]: <REPO>/compare/0.21.1...0.21.2
- Bump git2 from 0.18.3 to 0.19.0 ([#1212](https://github.com/cargo-generate/cargo-generate/pull/1212))
- Actually set `--depth 1` ([#1211](https://github.com/cargo-generate/cargo-generate/pull/1211))
</blockquote>
</p></details>
---
=> chore: release v0.21.2

Cargo.lock, Cargo.toml, src/args.rs
My motivation here was that when I run cargo generate, I find it difficult to find the options that are useful as there's no real order to the help output. This helps by injecting color, sorting the options into some reasonable sections, and shortening the longest option name.
=> feat: reformat help text in the style of cargo

CHANGELOG.md, Cargo.lock, Cargo.toml
* `cargo-generate`: 0.21.2 -> 0.21.3
<blockquote>
[0.21.3]: https://github.com/cargo-generate/cargo-generate/compare/0.21.2...0.21.3
- Reformat help text in the style of cargo ([#1223](https://github.com/cargo-generate/cargo-generate/pull/1223))
- Cancel in progres CI jobs when on the same run ([#1227](https://github.com/cargo-generate/cargo-generate/pull/1227))
- Tag option, see [#1222](https://github.com/cargo-generate/cargo-generate/pull/1222) ([#1226](https://github.com/cargo-generate/cargo-generate/pull/1226))
</blockquote>
</p></details>
---
=> chore: release v0.21.3

guide/src/templates/template_defined_placeholders.md
- Fix: Update `use_git` example where `boolean` should be `bool` 
- Fix: Update `use_git` example to remove `choices` field
- Fix: Update Supported Types "text" section so CTRL-D is rendered
- Style: Replace static text with a reference to 'supported types' section
- Style: Adjust whitespace
If you attempt to run the `use_git` example as it is currently you'll receive
> Error: invalid type for variable `use_git`: `boolean` possible values are `bool` and `string`
And, after you change it from `boolean` to `bool` you'll receive
> Error: bool type does not support `choices` field
The rendered page does not show CTRL-D
> "text": Represents a multiline string value. (terminated by hitting )
=> doc: Update 'use_git' example

CHANGELOG.md, Cargo.lock, Cargo.toml
* `cargo-generate`: 0.21.3 -> 0.22.0
<blockquote>
[0.22.0]: https://github.com/cargo-generate/cargo-generate/compare/0.21.3...0.22.0
- Update 'use_git' example ([#1191](https://github.com/cargo-generate/cargo-generate/pull/1191))
- Refine the docs so that the usage guide provides easier access to the ssh related docs
- Fix links and small adjustments
- Fix gitconfig `insteadOf` ([#874](https://github.com/cargo-generate/cargo-generate/pull/874)) ([#1265](https://github.com/cargo-generate/cargo-generate/pull/1265))
</blockquote>
</p></details>
---
=> chore: release v0.22.0

Cargo.toml
The ssh_key_from_memory feature has had no effect in the last 6 years. It will be removed in the next major release (https://github.com/rust-lang/git2-rs/pull/1087) and it will thus be an error to request it.
=> chore(deps): don't request ineffective ssh_key_from_memory feature from git2-rs

CHANGELOG.md, Cargo.lock, Cargo.toml
* `cargo-generate`: 0.22.0 -> 0.22.1 (✓ API compatible changes)
<blockquote>
[0.22.1]: https://github.com/cargo-generate/cargo-generate/compare/0.22.0...0.22.1
- Run e2e tests with git over ssh only on non PRs, for secret access reasons (#1287)
- Identify workspace project at parent folder and add as a member (#1342)
- Bump tempfile from 3.10.1 to 3.13.0 (#1281)
- Bump auth-git2 from 0.5.4 to 0.5.5 (#1277)
- Bump bstr from 1.9.1 to 1.10.0 (#1262)
- Clarify `.liquid` overwrite and ignore behavior ([#1295](https://github.com/cargo-generate/cargo-generate/pull/1295))
- Bump indexmap from 2.5.0 to 2.6.0 (#1297)
- Update deps
- Update rhai, fs-err, thiserror (#1351)
- Fix lint that wants a const fn (#1285)
- Fix tests and copy path …
=> chore: release v0.22.1

src/copy.rs, tests/integration/basics.rs
Fixes #1363 
- Introduced a new function `safe_copy_skip_existing` to introduce logic for skipping files that already exist, unless the overwrite flag is set, for non liquid files only.
- Added a test in src/copy.rs to cover new behavior
- Test to verify that files are copied if they don't exist.
- Test to ensure that files are not overwritten without the flag set.
- Test to allow overwriting files when the flag is set to true.
- Updated a test in `tests/integration/basic.rs` to include:
- Sucess in case of existance of non liquid file of same name.
These changes enhance the usability of the file copy functionality, ensuring safe file handling in various scenarios.
=> Enhance file copy behavior: Implement skipping existing files and allow overwriting with a flag

Cargo.lock, src/workspace_member.rs
- yet another fix for #1442 
- now also `cargo build --locked` works
Signed-off-by: Sven Kanoldt <sven@d34dl0ck.me>
=> fix: update cargo-util-schemas to 0.7.3 and fix optional type for package name

.github/workflows/build.yml
The issue is explained here: https://github.com/orgs/community/discussions/65321
In essence creating a pr from a workflow run with the gh token will not trigger the pull_request created event. 
The idea is to listen to an event that is also fired by using the API, this way the workflow should be triggered as if the PR created event was triggering.
Signed-off-by: Sven Kanoldt <sven@d34dl0ck.me>
=> fix(ci): fix that checks on release pr where not triggered

CHANGELOG.md, Cargo.lock, Cargo.toml
* `cargo-generate`: 0.23.1 -> 0.23.2 (✓ API compatible changes)
<blockquote>
[0.23.2]: https://github.com/cargo-generate/cargo-generate/compare/0.23.1...0.23.2
- Fix Cargo.toml to reflect always use version after breaking change in `cargo-util-schemas` ([#1459](https://github.com/cargo-generate/cargo-generate/issues/1459))
</blockquote>
</p></details>
---
This PR was generated with [release-plz](https://github.com/release-plz/release-plz/).
=> chore: release v0.23.2

Cargo.lock, Cargo.toml
Hello,
I'm a first time user and, when I tried installing cargo-generate, I got the same problem reported in #1468. I've updated cargo-util-schemas to 0.8.0 locally and all tests passed.
=> chore(deps): bump cargo-util-schemas to 0.8.0

CHANGELOG.md, Cargo.lock, Cargo.toml
* `cargo-generate`: 0.23.2 -> 0.23.3 (✓ API compatible changes)
<blockquote>
[0.23.3]: https://github.com/cargo-generate/cargo-generate/compare/0.23.2...0.23.3
- Bump cargo-util-schemas to 0.8.0 ([#1469](https://github.com/cargo-generate/cargo-generate/issues/1469))
</blockquote>
</p></details>
---
This PR was generated with [release-plz](https://github.com/release-plz/release-plz/).
=> chore: release v0.23.3

guide/src/templates/scripting.mini-example.md
fix syntax error for pre-script.rhai example
Error: ⛔   Failed executing script: pre-script.rhai
Caused by:
Syntax error: Expecting ';' to terminate this statement (line 4, position 1)
=> docs: fix syntax error for pre-script.rhai example

src/copy.rs, src/lib.rs
Caused by a regression in https://github.com/cargo-generate/cargo-generate/commit/a0dba72622b1ba903e0e7e484741d4380e303cf9.
```
(HEAD detached at a0dba72) $ ./target/debug/cargo-generate generate gibbz00/basic-things
⚠️   Favorite `gibbz00/basic-things` not found in config, using it as a git repository: https://github.com/gibbz00/basic-things.git
🤷   Project Name: test123
🔧   Destination: /tmp/test123 ...
🔧   project-name: test123 ...
🔧   Generating template ...
Error: ⛔   Failed executing script: cargo_generate/script.rhai
Caused by:
Runtime error: No such file or directory (os error 2)
```
From the commit before:
```
(HEAD detached at ea23bab) $ ./target/debug/cargo-generate generate gibbz00/basic-things
⚠️   Favorite `gibbz00/basic-things` not found in config, using it as a git …
```
=> fix: missing `.liquid` stripping in git templates

src/git/mod.rs, src/hooks/mod.rs, src/include_exclude.rs, src/lib.rs, src/template.rs, tests/integration/template_config_file/includes_and_excludes.rs
**Fix: Excluded files in templated paths are now properly handled**
Fix issue: #1514
**Problem**
Previously, when files were marked as excluded in the template configuration but were located within templated directory paths (e.g., `{{project-name}}/excluded-file`), the exclusion logic would simply skip processing them without considering that the directory path itself needed templating. This resulted in excluded files being ultimately ignored as they were not copied into the target directory.
**Objective**
Ensure that template exclusion rules work correctly regardless of whether the excluded files are in static or templated directory structures.
**Solution**
This fix enhances the exclusion handling logic in the `walk_dir` function to:
1. Apply filename substitution to excluded files: Even …
=> Fix: Excluded files in templated paths are now properly handled

CHANGELOG.md, Cargo.lock, Cargo.toml
* `cargo-generate`: 0.23.3 -> 0.23.4 (✓ API compatible changes)
<blockquote>
[0.23.4]: https://github.com/cargo-generate/cargo-generate/compare/0.23.3...0.23.4
- Fix syntax error for pre-script.rhai example ([#1479](https://github.com/cargo-generate/cargo-generate/issues/1479))
- Bump git2 from 0.20.1 to 0.20.2 ([#1485](https://github.com/cargo-generate/cargo-generate/issues/1485))
- Bump toml from 0.8.20 to 0.8.22 ([#1483](https://github.com/cargo-generate/cargo-generate/issues/1483))
- Bump auth-git2 from 0.5.7 to 0.5.8 ([#1493](https://github.com/cargo-generate/cargo-generate/issues/1493))
- Bump cargo-util-schemas from 0.8.0 to 0.8.1 ([#1488](https://github.com/cargo-generate/cargo-generate/issues/1488))
- Bump bstr from 1.11.3 to …
=> chore: release v0.23.4

src/absolute_path.rs, src/template_filters.rs
In some windows setups, the path tempdir generates is prefixed by `\\?\` making it a verbatim path. The current `canonicalize_path` function strips the prefix turning `\\?\C:\temp\...` into `\temp\...` which results in either a silent failure in the case of `file::delete` or a network error in the case of `file::listdir`
This PR fixes that issue by allowing verbatim disk paths
Fixes https://github.com/DioxusLabs/dioxus-template/issues/78
Fixes #1540
=> Fix verbatim disks in windows

CHANGELOG.md, Cargo.lock, Cargo.toml
* `cargo-generate`: 0.23.4 -> 0.23.5 (✓ API compatible changes)
<blockquote>
[0.23.5]: https://github.com/cargo-generate/cargo-generate/compare/0.23.4...0.23.5
- Bump toml from 0.8.23 to 0.9.2 ([#1521](https://github.com/cargo-generate/cargo-generate/issues/1521))
- Fix verbatim disks in windows ([#1539](https://github.com/cargo-generate/cargo-generate/issues/1539))
</blockquote>
</p></details>
---
This PR was generated with [release-plz](https://github.com/release-plz/release-plz/).
=> chore: release v0.23.5
